### ISSUE TITLE
webpack build fail about bootstrap.css

### ISSUE THREAD

**Issue by yuhaocan** [summernote/react-summernote#33]
ERROR in ./~/bootstrap/dist/css/bootstrap.css
Module parse failed: /Users/julyyu/FrontEnd-Project/CPPCC.Web/node_modules/bootstrap/dist/css/bootstrap.css Unexpected token (7:5)
You may need an appropriate loader to handle this file type.
|  */
| /*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */
| html {
|   font-family: sans-serif;
|   -webkit-text-size-adjust: 100%;
 @ ./src/js/components/common/RichTextEditor.js 31:0-43
 @ ./src/js/components/home/HomeNoticeAdd.js
 @ ./src/js/services/sliderContent.js
 @ ./src/js/containers/Application.jsx
 @ ./src/js/router/Router.jsx
 @ ./src/app.jsx
 @ multi ./src/app webpack-dev-server/client?http://localhost:3000 webpack/hot/only-dev-server
webpack: Failed to compile.

use ReactSummernote same as  Demo

i cant reslove this problem, please help~

**Comment by Gukulkan** [comment]
I had the same problem, try to add 
    "file-loader"
    "url-loader"
    "css-loader"
    "style-loader"
It helps for me.
