### ISSUE TITLE
How can I use summernote api in this react project?

### ISSUE THREAD

**Issue by chyxyjh** [summernote/react-summernote#35]
I want to get the result user has input, and I have meet some trouble.
In summernote's doc, I can get the result by using `$('#summernote').summernote('code');`.
What should I do to get the same effect？Should I also import jQuery?
Thanks so much!!

**Comment by philipcressler** [comment]
Did you ever find out how to do this?

**Comment by ykhleeh** [comment]
up?

**Comment by mmiszy** [comment]
There's an easy way to access summernote APIs without the need to modify the component. You should just use `ref`:

```jsx
<ReactSummernote
  ref={el => this.wysiwygEditorRef = el}
/>
```

and then somewhere in your code:

```jsx
this.wysiwygEditorRef.editor.summernote('code') // for example
```
