### ISSUE TITLE
Disabled state

### ISSUE THREAD

**Issue by inoyakaigor** [summernote/react-summernote#39]
Hi!
I developing control panel of mail subscriptions and i have on some pages functionality of view content of letters which was sended. In this state all controls are disabled for edit but in ReactSummernote have not ways to control it.
Can you add props **`disabled={true|false}`**?
Also i think this functionality will be helpfully not only for me

**Comment by hoangvn2404** [comment]
`<ReactSummernote
        disabled={!this.state.edit}
        value={this.state.content}
        onChange={this.onChange}
        options={{
          toolbar: [
            ['style', ['bold', 'italic', 'underline']],
            ['font', ['fontsize', 'color']],
            ['paragraph', ['style', 'ol', 'ul']],
            ['clear', ['clear']],
            ['codeview', ['codeview']]
          ]
        }}
      />`

hey @inoyakaigor there is already disabled props, I had use it on my project

**Comment by FrancisVila** [comment]
Hi, 
I set **disabled={true}** and editing still remains active. Here's the exact syntax:
`<SummernoteEditor` suggestions={getSuggestion()} text={this.textSummer} onChange={this.onChangeSummer} disabled={true}  />`
