### ISSUE TITLE
<ReactSummernote value = 'content' /> doesn't work after update from 2.0.0 to 2.0.2

### ISSUE THREAD

**Issue by dmytrotus** [summernote/react-summernote#85]
Hello. I notices that "value" doesn't work in version, 2.0.2. In Version 2.0.0 works fine.
`<ReactSummernote
                        value = {state.content}
                        onChange={onChange}
                      />`

**Comment by minaairsupport** [comment]
I have the same issue

**Comment by madist** [comment]
me too..

**Comment by chassteel** [comment]
@Vnkitaev please could you publish 2.0.2 to Github?  Thanks!

**Comment by silkyland** [comment]
Same here "value" prop bug

**Comment by bhoomiagrawal** [comment]
use "children" instead of "value"

**Comment by annguyen97dev** [comment]
> use "children" instead of "value"

Awsome, thank u a lot <3

**Comment by willcorum** [comment]
When setting the value via children it does not display text with markup. If I pass in <b>Test</b> it shows as that exact string, instead of the the word Test in bold.

**Comment by willcorum** [comment]
Was is something I said?

**Comment by dmytrotus** [comment]
> Was is something I said?

No, I just did't use this package for a long time to I decided to close tha issue. Probably some variants under messages works...
